# Generated by Django 4.1.1 on 2022-10-25 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_link', models.URLField(verbose_name='Channel Link')),
                ('ch_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Channel Name')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Link')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubescraper.youtubechannel')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('youtube_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubescraper.youtubelink')),
            ],
        ),
    ]
